### ISSUE TITLE
Broken ServiceType

### ISSUE THREAD

**Issue by avivey** [pokitdok/apidocs-v4#246]
`professional_intensive_cardiac_rehabilitation_` shows up in Eligibility/ServiceTypes table without a code:

![image](https://cloud.githubusercontent.com/assets/1530242/25880746/12ef2086-34ee-11e7-847b-1da1f7ed0e8e.png)

**Comment by denisekgosnell** [comment]
@avivey https://github.com/pokitdok/apidocs-v4/pull/247

**Comment by denisekgosnell** [comment]
Fix deployed: https://platform.pokitdok.com/documentation/v4/#eligibility

Thank you @avivey
